// angular-blog/src/app/components/blog-page/blog-page.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import * as moment from 'moment';
import { ToastrService } from 'ngx-toastr';
import { Post } from 'src/app/models/Post';
import { User } from 'src/app/models/User';
import { FakeDataService } from 'src/app/services/fake-data-service.service';
import { SaveModalComponent } from '../save-modal/save-modal.component';

@Component({
  selector: 'app-blog-page',
  templateUrl: './blog-page.component.html',
  styleUrls: ['./blog-page.component.scss']
})
export class BlogPageComponent implements OnInit {
  user: User;
  posts: Post[];
  
  constructor(
    private fakeDataService: FakeDataService,
    private dialog: MatDialog,
    private toastr: ToastrService) { }

  private loadPosts() {
    this.fakeDataService.getPosts()
      .subscribe(res => {
        this.posts = res;
      });
  }

  ngOnInit(): void {
    this.fakeDataService.getUser()
      .subscribe(res => {
        this.user = res[0];
      });
    this.loadPosts();
  }
  
  formatDate(date: Date) {
    const momentDate = moment(date);
    return momentDate.format('DD MMMM YYYY'); 
  }

  onCreate() {
    const dialogRef = this.dialog.open(SaveModalComponent, {
      width: '370px'
    });

    dialogRef.afterClosed().subscribe(result => {
      if (!!result) {
        this.fakeDataService.addPost(result)
           .subscribe(_ => {
             this.loadPosts();
             this.toastr.success('Post successfully created!');
         });
      }
    });
  }

  onDelete(post: Post) {
    this.fakeDataService.deletePost(post.id)
       .subscribe(_ => {
         this.loadPosts();
         this.toastr.info(`Post ${post.title} was successfully deleted!`);
     });
  }
  
  onEdit(post: Post) {
    const dialogRef = this.dialog.open(SaveModalComponent, {
      width: '370px',
      data: post
    });

    dialogRef.afterClosed().subscribe(result => {
      if (!!result) {
        this.fakeDataService.updatePost(result)
           .subscribe(_ => {
             this.loadPosts();
             this.toastr.success('Post successfully updated!');
         });
      }
    });
  }
  
  onSave = (post: Post) => {
    // if (!!editedPost) {
    //   this.fakeDataService.updatePost(post)
    //     .then(_ => {
    //       this.loadPosts();
    //       toast.success('Post successfully updated');
    //     });

    //   return;
    // }

    // this.fakeDataService.addPost(post)
    //   .then(_ => {
    //     this.loadPosts();
    //     toast.success('Post successfully created');
    //   });
  }
}

<div class="blogPage">
    <div class="user">
        <img src="{{ user?.avatar }}" />
        <div>
            <p>{{ user?.userName }}</p>
            <p>{{ user?.description }}</p>
        </div>
    </div>
    <div class="line">
        <p>How I try to stay a float while being a frontend developer</p>
    </div>

    <div class="posts">
        <div class="post newPost" (click)="onCreate()">
            Create new post
        </div>
        <div class="post" *ngFor="let post of posts">
            <div class="top">
                <p class="title">{{ post.title }}</p>
                <div class="actions">
                    <p class="edit" (click)="onEdit(post)">Edit</p>
                    <p class="delete" (click)="onDelete(post)">Delete</p>
                </div>
            </div>
            <p class="description">{{ post.description }}</p>
            <div class="bottom">
                <p>{{ formatDate(post.createdAt) }}</p>
                <p class="likes" *ngIf="post.likes > 0">
                    <svg id="color" enable-background="new 0 0 24 24" height="512" viewBox="0 0 24 24" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m11.466 22.776c.141.144.333.224.534.224s.393-.08.534-.224l9.594-9.721c4.001-4.053 1.158-11.055-4.532-11.055-3.417 0-4.985 2.511-5.596 2.98-.614-.471-2.172-2.98-5.596-2.98-5.672 0-8.55 6.984-4.531 11.055z" fill="#f44336"/></svg>
                    {{ post.likes }}
                </p>
            </div>
        </div>
    </div>

    <!-- <SaveModal 
        isModalOpened={isModalOpened} 
        closeModal={() => setModalOpened(false)} 
        onSave={onSave} 
        editedPost={editedPost}
    />
    <ToastContainer /> -->
</div>

// react-blog-ts/src/Components/blog-page/BlogPage.tsx
import moment from 'moment';
import React, { useEffect, useState } from 'react';
import { Post } from '../../models/Post';
import { User } from '../../models/User';
import fakeDataService from '../../services/fakeDataService';
import styles from './styles.module.scss';
import heart from '../../heart.svg';
import SaveModal from '../save-modal/SaveModal';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const BlogPage: React.FunctionComponent = () => {
    const [user, setUser] = useState<User>();
    const [posts, setPosts] = useState<Post[]>();
    const [editedPost, setEditedPost] = useState<Post>();
    const [isModalOpened, setModalOpened] = useState<boolean>(false);
    
    useEffect(() => {
        fakeDataService.getUser()
            .then(res => {
                setUser(res.data[0]);
            })
    }, []);
    
    const getPosts = () => {
        fakeDataService.getPosts()
            .then(res => {
                setPosts(res.data);
            });
    }

    useEffect(() => {
        getPosts();
    }, []);

    const formatDate = (date: Date) => {
        const momentDate = moment(date);
        return momentDate.format('DD MMMM YYYY'); 
    }

    const onCreate = () => {
        setEditedPost(undefined);
        setModalOpened(true);
    };

    const onSave = (post: Post) => {
        if (!!editedPost) {
            fakeDataService.updatePost(post)
                .then(_ => {
                    getPosts();
                    toast.success('Post successfully updated');
                });

            return;
        }

        fakeDataService.addPost(post)
            .then(_ => {
                getPosts();
                toast.success('Post successfully created');
            });
    };

    const onDelete = (post: Post) => {
        fakeDataService.deletePost(post.id)
            .then(_ => {
                toast.info(`Post ${post.title} was successfully deleted!`);
                getPosts();
            });
    }

    const onEdit = (post: Post) => {
        setEditedPost(post);
        setModalOpened(true);
    }

    return (
        <div className={styles.blogPage}>
            <div className={styles.user}>
                <img src={user?.avatar} />
                <div>
                    <p>{user?.userName}</p>
                    <p>{user?.description}</p>
                </div>
            </div>
            <div className={styles.line}>
                <p>How I try to stay a float while being a frontend developer</p>
            </div>

            <div className={styles.posts}>
                <div className={`${styles.post} ${styles.newPost}`} onClick={onCreate}>
                    Create new post
                </div>
                {posts?.map(post => (
                    <div className={styles.post} key={post.id}>
                        <div className={styles.top}>
                            <p className={styles.title}>{post.title}</p>
                            <div className={styles.actions}>
                                <p className={styles.edit} onClick={() => onEdit(post)}>Edit</p>
                                <p className={styles.delete} onClick={() => onDelete(post)}>Delete</p>
                            </div>
                        </div>
                        <p className={styles.description}>{post.description}</p>
                        <div className={styles.bottom}>
                            <p>{formatDate(post.createdAt)}</p>
                            {
                                post.likes !== undefined && post.likes > 0 ? (
                                    <p className={styles.likes}><img src={heart} width="10px"/>{post.likes}</p>
                                ) : ''
                            }
                            
                        </div>
                    </div>
                ))}
            </div>
            <SaveModal 
                isModalOpened={isModalOpened} 
                closeModal={() => setModalOpened(false)} 
                onSave={onSave} 
                editedPost={editedPost}
            />
            <ToastContainer />
        </div>
    );
}

export default BlogPage;
